sudo: required

langeuge: generic

services:
  - docker

before_install:
  - echo "start Creating an image with dockerfile"
  - docker built -t moon/docker-react-app -f Dockerfile.dev .

script:
  - docker run -e CI=true moon/docker-react-app npm run test -- --coverage

after_success:
  - echo "Test Success"